name: Validate Build

on:
  pull_request:
    branches: [ master ]

jobs:
  automated-testing:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build Project
        run: |
          echo "hi"
